### ISSUE TITLE
挂代理抓取不成功

### ISSUE THREAD

**Issue by weique** [KanagiMiss/MoeDownloader#1]
一共down下来四个头像。终端界面返回信息如下：
 $  python catch.py --proxy 127.0.0.1:1160 caoliu
Processing caoliu...
===============   start   ===============
===============   loading page 1   ===============
Thread 1:http://t66y.com/htm_data/16/1605/1921922.html
[原創投稿][達蓋爾********************_]**_******************_实录[33P]/
        =>Images/caoliu/[原創投稿][達蓋爾*********************]**_******************_实录[33P]/0
        =>Images/caoliu/[原創投稿][達蓋爾*********************]**_******************_实录[33P]/1
        =>Images/caoliu/[原創投稿][達蓋爾*********************]**_******************_实录[33P]/2
        =>Images/caoliu/[原創投稿][達蓋爾*********************]**_******************_实录[33P]/3
        =>Images/caoliu/[原創投稿][達蓋爾*********************]**_******************_实录[33P]/4
Traceback (most recent call last):
  File "catch.py", line 792, in <module>
    main()
  File "catch.py", line 787, in main
    args.func(args)
  File "catch.py", line 687, in caoliu
    cl.Download()
  File "catch.py", line 540, in Download
    res = self.DoFetch(domain)
  File "catch.py", line 209, in DoFetch
    self.FetchPageHtml(html);
  File "catch.py", line 236, in FetchPageHtml
    res = self.FetchThreadHtml(threadurl)
  File "catch.py", line 300, in FetchThreadHtml
    self.FetchImgLinksFromThread(html);
  File "catch.py", line 318, in FetchImgLinksFromThread
    res = self.download_file(href)
  File "catch.py", line 387, in download_file
    r = session.get(url)
  File "d:\Python27\lib\site-packages\requesocks\sessions.py", line 220, in get
    return self.request('get', url, *_kwargs)
  File "d:\Python27\lib\site-packages\requesocks\sessions.py", line 203, in request
    r.send(prefetch=prefetch)
  File "d:\Python27\lib\site-packages\requesocks\models.py", line 596, in send
    timeout=self.timeout,
  File "d:\Python27\lib\site-packages\requesocks\packages\urllib3\connectionpool.py", line 456, in urlopen
    body=body, headers=headers)
  File "d:\Python27\lib\site-packages\requesocks\packages\urllib3\connectionpool.py", line 332, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "d:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "d:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "d:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "d:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "d:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "d:\Python27\lib\site-packages\requesocks\packages\urllib3\connectionpool.py", line 159, in connect
    self._tunnel()
  File "d:\Python27\lib\httplib.py", line 805, in _tunnel
    self._tunnel_port))
TypeError: %d format: a number is required, not NoneType

**Comment by misskanagi** [comment]
可以试试看指定代理类型，如果是http代理用：
python catch.py --proxy  http://127.0.0.1:1160 caoliu
如果是socks代理可以用：
python catch.py --proxy socks://127.0.0.1:1160 caoliu
